### ISSUE TITLE
HTTP error 500

### ISSUE THREAD

**Issue by eddie1707** [AnemaNL/SMT-issues#3]
Indien ergens een veld leeg is en je klikt op opslaan verschijnt html error 500. Tegengekomen bij tellen en product aanpassen

**Comment by GertJanFrl** [comment]
https://user-images.githubusercontent.com/1015752/221017981-bc4e7bd7-964b-411f-92ab-c9eb3dfc3192.MOV

https://user-images.githubusercontent.com/1015752/221018010-8d4c0cfe-4be9-457d-80be-206b3f7e5ded.MOV

**Comment by GertJanFrl** [comment]
Hoi Edwin!

Excuses voor de late reactie maar dit probleem is al enige tijd geleden opgelost!

**Comment by eddie1707** [comment]
Dit issue is teruggekeerd bij het uitvoeren van een telling! Na het klikken op 'Telling opslaan' terwijl er een veld leeg is verschijnt de foutmelding zoals te zien op bijgevoegd screenshot.
![Screenshot 2023-06-09 at 21 55 08](https://github.com/Dagend/Managend-issues/assets/6514361/7799d068-e1a4-4293-929e-2aecb2cd3e93)

**Comment by GertJanFrl** [comment]
@eddie1707 Zou jij mij kunnen laten weten waar en hoe dit probleem gebeurde? Hoe kan ik dit reproduceren?
