### ISSUE TITLE
Verkeerde titel bij afdelingen

### ISSUE THREAD

**Issue by eddie1707** [AnemaNL/SMT-issues#6]
Bij afdelingen staat 2 keer de titel "Inactieve afdelingen". hier zou één van beide "actieve afdelingen" moeten weergeven

![Screenshot 2023-06-09 at 21 49 34](https://github.com/Dagend/Managend-issues/assets/6514361/bd6f7cce-3d58-46c4-9c3b-7da127df3e62)

**Comment by GertJanFrl** [comment]
Bedankt voor het melden van deze tekst fout, teksten zijn aangepast en probleem is dus daarbij opgelost.
