### ISSUE TITLE
Fout bij product bewerken

### ISSUE THREAD

**Issue by eddie1707** [AnemaNL/SMT-issues#7]
Bij het bewerken van een product onder 'assistent manager' -> 'Balansen' blijft het scherm blanco na het klikken op het bewerk potloodje naast het artikel. Tevens werken de knoppen van het menu niet meer op deze pagina.

![Screenshot 2023-06-09 at 21 51 32](https://github.com/Dagend/Managend-issues/assets/6514361/13d0acd3-0933-42c0-9eb4-4de28b2a9c03)

**Comment by GertJanFrl** [comment]
Bedankt voor het melden hiervan. Dit probleem is nu opgelost!
